version: '3.8'
services:

  # Docker connection string for local machine: postgres://postgres:postgres@localhost:5432/

  postgres:
    image: postgres:13.5    # 1
    restart: always
    environment:            # 2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:                # 3
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'         # 4
  
  graphql:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/hackernews-db
    ports:
      - '3000:3000'
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres: